'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class Course
        Public Property CourseId As Integer
        Public Property CourseCode As String
        Public Property CourseName As String
        Public Property CreditHours As Nullable(Of Integer)
    
    End Class

End Namespace
