'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class CourseRegistration
        Public Property CourseRegistrationId As Integer
        Public Property CourseId As Nullable(Of Integer)
        Public Property StudentId As Nullable(Of Integer)
        Public Property RegistrationTime As Nullable(Of Date)
    
    End Class

End Namespace
