'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class Student
        Public Property StudentId As Integer
        Public Property StudentName As String
        Public Property StudentRegNo As String
        Public Property StudentSemester As Nullable(Of Integer)
    
    End Class

End Namespace
